class Config(object):
    def __init__(self):
        self.TRAININGSET_DIR = './DataSet/University_data/train_sample_all_cr_v2.json'
        self.VALIDATIONSET_DIR = './DataSet/University_data/valid_sample_without_target_cr_v2.json'
        self.TESTSET_DIR = './DataSet/University_data/target_set_cr_v2.json'
        self.NEG_SAMPLES = './DataSet/University_data/neg_sample_cr_v2.pickle'
        self.MODEL_DIR = './DataSet/University_data/runs_cr_genrec_v1/'
        self.cuda = False
        self.clip = 10
        #self.epochs = 200
        self.epochs = 10 #25
        #self.batch_size = 256
        self.batch_size = 32
        #self.seq_len = 20
        self.seq_len = 20
        self.learning_rate = 0.01  # Initial Learning Rate
        self.log_interval = 1  # num of batches between two logging
        self.basket_pool_type = 'max'  # ['avg', 'max']
        self.attention_layer_num = 2 # 1 2 3
        self.dropout = 0.3 #0.4 0.5
        #self.num_product = 26991+1 
        # self.num_product = 3881+1
        self.num_product = 618+1
        #self.num_product = 617
        #self.num_product = 601
        #self.embedding_dim = 32  # Embedding Layer
        self.embedding_dim = 64 # 8 16 32 
        #self.neg_num = 500  
        self.neg_num = 600
        self.top_k = 10  # Top K 
